### ISSUE TITLE
4.5.3 should not be listed...

### ISSUE THREAD

**Issue by philwareham** [textpattern-community/textpattern-releases#1]
...due to an error in the package. Please remove it. Thanks!

**Comment by petecooper** [comment]
Hi @philwareham - only just saw this...

I'd respectfully argue that 4.5.3 _should_ be listed, perhaps with a caveat that it should not be used.

It was released, it worked as expected at the time (at least the .zip did), and it was a packaging error in the .tar.gz that caused it be pulled and repackaged.

There are versions of Textpattern here with known (and, crucially, subsequently resolved) vulnerabilities. They're still downloadable from the Textpattern main site -- that doesn't make them any less valuable/useful.

**Comment by philwareham** [comment]
OK, no worries then. Closing.
